/* ******************************************************************************
 * The MIT License
 * Copyright (c) 2012 Bruno Ranschaert
 * lib-scripty
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
package branscha.scripty.spec.map;

import branscha.scripty.annot.ScriptyBindingParam;
import branscha.scripty.annot.ScriptyParam;
import branscha.scripty.parser.Context;
import branscha.scripty.parser.Eval;

import java.lang.annotation.Annotation;
import java.lang.reflect.Method;
import java.lang.reflect.Parameter;
import java.util.Map;

/**
 * Converts the {@link ScriptyParam} annotations and other known Scripty types into argument mappers to construct
 * the inputs for the command method.
 */
public class CmdMethodInjectorBuilder {

    private static final String ERR010 = "CmdMethodInjectorBuilder/010: Using both @ScriptyParam and @ScriptyBindingParam at the same time is not possible for parameter '%s' in method '%s'.";
    private static final String ERR020 = "CmdMethodInjectorBuilder/020: There is no argument named '%s' to inject in the parameter '%s' of method '%s'.";

    /**
     * Construct a set of argument mappings that map arguments specified in the argument list to command method
     * parameters as indicated by the {@link ScriptyParam} annotations and {@link ScriptyBindingParam} annotations
     * or the class names Eval, Context and Object[].
     *
     * @param method The command method for wich to create the argument mapping.
     * @param argMappings The named argument mappers generated by the {@link branscha.scripty.spec.args.ArgListBuilder}.
     * @return The list of mappings that will be applied to construct the method call arguments.
     * @throws ArgMappingException
     */
    public static CmdMethodInjector buildArgMapping(Method method, Map<String, ArgMapping> argMappings)
    throws ArgMappingException {
        CmdMethodInjector injector = new CmdMethodInjector();

        String methodName = method.getName();
        Parameter[] parameters = method.getParameters();
        for(Parameter p : parameters) {
            Annotation[] annotations = p.getAnnotations();
            Class<?> paramType = p.getType();
            String paramName = p.getName();

            ArgMapping argMapping = buildSingleMapping(methodName, paramName, paramType, annotations, argMappings);
            injector.addArgMapping(argMapping);
        }
        return injector;
    }

    private static ArgMapping buildSingleMapping(
            String methodName, String paramName, Class<?> paramClass,
            Annotation[] annotations, Map<String, ArgMapping> argMappings)
    throws ArgMappingException {

        if (annotations.length <= 0) {
            // If there are no parameter annotations, we check if
            // the parameter types is one of the well known types.

            if (paramClass.isAssignableFrom(Eval.class)) {
                return new EvalMapping();
            }
            else if (paramClass.isAssignableFrom(Context.class)) {
                return new ContextMapping();
            }
            else if (paramClass.isArray() && paramClass.getComponentType().isAssignableFrom(Object.class)) {
                return new CompleteMapping();
            }
        }
        else {
            ScriptyParam paramAnnotation = null;
            ScriptyBindingParam bindingAnnotation = null;

            for (Annotation annotation : annotations) {
                if (annotation instanceof ScriptyParam) paramAnnotation = (ScriptyParam) annotation;
                else if (annotation instanceof ScriptyBindingParam) bindingAnnotation = (ScriptyBindingParam) annotation;
            }

            if (paramAnnotation != null && bindingAnnotation != null) {
                throw new ArgMappingException(String.format(ERR010, methodName, paramName));
            }
            else if (paramAnnotation != null) {
                String argName = paramAnnotation.value();
                if (argMappings != null && argMappings.containsKey(argName)) return argMappings.get(argName);
                else throw new ArgMappingException(String.format(ERR020, argName, paramName, methodName));
            }
            else if (bindingAnnotation != null) {
                String bindingName = bindingAnnotation.value();
                boolean exceptionIfNull = bindingAnnotation.unboundException();
                return new BindingMapping(bindingName, exceptionIfNull);
            }
        }

        // Default is null value.
        return new NullMapping();
    }
}
